# These are supported funding model platforms

github: [Kyonax]
patreon: synk_kyonax
community_bridge: bot-discord-synchronous
paypal: ['https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=5LY2Y46Q7DSWL&source=url']
